name: Mirror and run GitLab CI

on: # Controls when the action will run.
  workflow_dispatch:
  push: # Please add your branch down here if wanted. A build will be triggerd for each push.
    branches: [HDLTopSim, merge_for_mc]
  pull_request:
    branches: [master, HDLTopSim]
    
env:
  current_branch: 'master' # fallback branch

jobs:
  mirror_trig: # https://github.com/marketplace/actions/mirror-to-gitlab-and-run-gitlab-ci
    name: mirror_trig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Debug
      run: |
        echo "github.ref = ${{ github.ref }}"
    - name: Redefine branch on pull_request
      if: github.event_name == 'pull_request'
      run: |
        echo "current_branch=$(echo ${{ github.head_ref }})" >> $GITHUB_ENV
    - name: Redefine branch on push
      if: github.event_name == 'push'
      run: |
        echo "current_branch=$(echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||')" >> $GITHUB_ENV
    - name: Mirror + trigger CI
      uses: aperloff/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.cern.ch/cms-l1tk/firmware-hls"
      env:
        GITLAB_HOSTNAME: "gitlab.cern.ch"
        GITLAB_USERNAME: "cms-l1tk"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }} # Generate here: https://gitlab.com/profile/personal_access_tokens and add to GitHub secrets
        GITLAB_PROJECT_ID: "89897"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://help.github.com/en/articles/virtual-environments-for-github-actions#github_token-secret
        CHECKOUT_BRANCH: ${{ env.current_branch }} # New non-GITHUB variable to make push and PR work
        REMOVE_BRANCH: "true"
