name: HLS build on lnxfarm327
env:
  VIVADO_VERSION: '2019.2'
  VIVADO_PATH_SH: /nfs/data41/software/Xilinx/Vivado/2019.2/settings64.sh
  GLOBAL_RUN_CMD: cd project && source echo(${{ VIVADO_PATH_SH }}) && vivado_hls -f "script_CMD.tcl"

on: # Controls when the action will run.
  push: # Please add your branch down here if wanted. A build will be triggerd for each push.
    branches: [master, feat_actions] 
  #pull_request: # !!! SECURITY ISSUE: Only enable if repository is private. !!! because of self-hosted runner
  #  branches: [ master ] # !!! SECURITY ISSUE: Only enable if repository is private. !!!
jobs: # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  hls-build: # Job name
    runs-on: self-hosted # The type of runner that the job will run on
    steps: # Steps represent a sequence of tasks that will be executed as part of the job
    - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Debug # Script name
      run: |
        pwd; ls -a; ls -a project; ls -a $GITHUB_WORKSPACE; # Debug
#        $(echo ${{ env.GLOBAL_RUN_CMD }})
    - name: MC # Script name
      id: MC
#      env:
#        RUN_CMD: $(echo ${{ env.GLOBAL_RUN_CMD }} | sed -E 's|CMD|echo(${{ jobs.<job_id>.steps.id }})|')
#      run: ${{ RUN_CMD }}
      run: |
        cd project
#        source $VIVADO_PATH_SH
#        vivado_hls -f "script_MC.tcl"
    - name: Upload results
      uses: actions/upload-artifact@v1
      with:
        name: MC
        path: project/match_calc/solution1/syn/report/MatchCalculatorTop_csynth.rpt
    - name: ME # Script name
      run: |
        cd project
        source $VIVADO_PATH_SH
        vivado_hls -f "script_ME.tcl"
    - name: Upload results
      uses: actions/upload-artifact@v1
      with:
        name: ME
        path: project/matchengine/solution1/syn/report/MatchEngineTopL3_csynth.rpt
    - name: PR # Script name
      run: |
        cd project
        source $VIVADO_PATH_SH
        vivado_hls -f "script_PR.tcl"
    - name: Upload results
      uses: actions/upload-artifact@v1
      with:
        name: PR
        path: project/projrouter/solution1/syn/report/ProjectionRouterTop_csynth.rpt
    - name: TC # Script name
      run: |
        cd project
        source $VIVADO_PATH_SH
        vivado_hls -f "script_TC.tcl"
    - name: Upload results
      uses: actions/upload-artifact@v1
      with:
        name: TC
        path: project/trackletCalculator/solution1/syn/report/TrackletCalculator_L1L2G_csynth.rpt
    - name: TE # Script name
      run: |
        cd emData/TE
        ./download.sh
        cd ../../project
        source $VIVADO_PATH_SH
        vivado_hls -f "script_TE.tcl"
    - name: Upload results
      uses: actions/upload-artifact@v1
      with:
        name: TE
        path: project/trackletengine/solution1/syn/report/TrackletEngineTop_csynth.rpt
